// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7PxeHdadfLb1NJeVbBM5bwhWlfhBLQc0',
    appId: '1:804177700433:web:d4791776a5169c75197a70',
    messagingSenderId: '804177700433',
    projectId: 'sistema-de-incidencias-832c1',
    authDomain: 'sistema-de-incidencias-832c1.firebaseapp.com',
    storageBucket: 'sistema-de-incidencias-832c1.appspot.com',
    measurementId: 'G-88FVR5WNVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATiTGBGLR0Wshz2lARERODyb9SPy7XxfA',
    appId: '1:804177700433:android:ac58c616ccad8868197a70',
    messagingSenderId: '804177700433',
    projectId: 'sistema-de-incidencias-832c1',
    storageBucket: 'sistema-de-incidencias-832c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9AsrkH8u8nCz_4VWmhWnpHRr5VlEhAPM',
    appId: '1:804177700433:ios:e9d3ffa28b1e6b17197a70',
    messagingSenderId: '804177700433',
    projectId: 'sistema-de-incidencias-832c1',
    storageBucket: 'sistema-de-incidencias-832c1.appspot.com',
    androidClientId: '804177700433-3jnbufu979ikiggj8c75emmgl0uta75p.apps.googleusercontent.com',
    iosClientId: '804177700433-clp79birnehbecni2244sbp8en4bb2i9.apps.googleusercontent.com',
    iosBundleId: 'com.example.miCredencialDigital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9AsrkH8u8nCz_4VWmhWnpHRr5VlEhAPM',
    appId: '1:804177700433:ios:8d27f5722b07385a197a70',
    messagingSenderId: '804177700433',
    projectId: 'sistema-de-incidencias-832c1',
    storageBucket: 'sistema-de-incidencias-832c1.appspot.com',
    androidClientId: '804177700433-3jnbufu979ikiggj8c75emmgl0uta75p.apps.googleusercontent.com',
    iosClientId: '804177700433-iq4nil7hcqr4pjt75g904ulofip7sak9.apps.googleusercontent.com',
    iosBundleId: 'com.example.miCredencialDigital.RunnerTests',
  );
}
